apiVersion: v1 
kind: Deployment    
metadata:              
  name: springboot-k8s
spec:                
  selector:         
    matchLabels:
      app: springboot-k8s
  replicas: 3        
  template:
    metadata:
      labels:        
        app: springboot-k8s
    spec:
      containers:
        - name: springboot-k8s
          image: ayushwebkul/java-app:${BUILD_NUMBER}
          ports:
            - containerPort: 8080

